version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"  # Flask app
      - "5002:5002"  # MLflow server
    volumes:
      - ./models:/app/models
      - ./mlflow_data:/app/mlflow_data
      - ./tuning_results:/app/tuning_results
      - ./datasets:/app/datasets
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - MLFLOW_TRACKING_URI=http://localhost:5002
    restart: unless-stopped 