channels:
- conda-forge
dependencies:
- python=3.11.11
- pip<=24.3.1
- pip:
  - mlflow==2.6.0
  - jaraco-collections==5.1.0
  - jaraco-context==5.3.0
  - jaraco-functools==4.0.1
  - jaraco-text==3.12.1
  - more-itertools==10.3.0
  - numpy==1.24.3
  - packaging==23.2
  - pandas==2.0.3
  - pillow==11.1.0
  - protobuf==4.25.6
  - requests==2.31.0
  - scipy==1.15.2
  - tensorflow-macos==2.13.0
  - tensorflow==2.13.0
name: mlflow-env
