name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Debug - Print Docker Info
        run: |
          echo "Starting Docker login debug..."
          if [[ -n "${{ secrets.DOCKERHUB_USERNAME }}" ]] && [[ -n "${{ secrets.DOCKERHUB_TOKEN }}" ]]; then
            echo "Using username: ${{ secrets.DOCKERHUB_USERNAME }}"
            echo "Both DOCKERHUB_USERNAME and DOCKERHUB_TOKEN are available"
          else
            echo "Missing required secrets"
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ddm501-mse:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/ddm501-mse:${{ github.sha }} 