name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: 9davenguyen
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Debug - Print Docker Info
        run: |
          echo "Starting Docker login debug..."
          echo "Using username: $DOCKER_USERNAME"
          echo "Checking if secrets are available..."
          if [ -n "$DOCKER_PASSWORD" ]; then
            echo "Token is available"
            echo "Token length: ${#DOCKER_PASSWORD}"
          else
            echo "Token is NOT available"
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/ddm501-mse:latest
            ${{ env.DOCKER_USERNAME }}/ddm501-mse:${{ github.sha }} 