name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Debug - Print Docker Info
        run: |
          echo "Starting Docker login debug..."
          echo "Using username: 9davenguyen"
          echo "Checking if secrets are available..."
          if [ -n "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "Token is available"
            echo "Token length: ${#TOKEN}"
          else
            echo "Token is NOT available"
          fi
        env:
          TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u 9davenguyen --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            9davenguyen/ddm501-mse:latest
            9davenguyen/ddm501-mse:${{ github.sha }} 